---
title: "Consensus Visualization"
author: "Maura Kautz"
date: "2024-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
library(tidyverse)
library(knitr)
library(grDevices)
library(extrafont)
```

```{r, echo=FALSE, message=FALSE}
aml_counts <- read_tsv("/Users/maurakautz/Downloads/llcombo8_consensus_counts.tsv")

# Creating a data frame of sum of all counts for each structural variant by caller

aggregate_counts <- aml_counts %>% 
  group_by(SV, Caller) %>% 
  summarize(Total_Counts = sum(Count)) %>% 
  ungroup()
```

```{r, echo=FALSE, message=FALSE, fig.width=10}
#Used following steps to change font in console:

#install.packages("extrafont")
#library(extrafont)
#font_import()
#loadfonts(device="all")

#Fred Hutch Hex Codes:
#A74AC7 (purple)
#FCB001 (yellow)
#00C0D5 (blue)
#19355C (navy) 

consensus_plot <- ggplot(aggregate_counts, aes(x=SV, y=Total_Counts, fill=Caller)) + #plotting SV counts by caller
  geom_bar(position=position_dodge(), stat="identity") +
  theme_bw() +
  xlab("Structural Variant Type") +
  ylab("Count") +
  ggtitle("Frequency of Structural Variants by Caller: Full Consensus Data") +
  scale_fill_manual(values = c("#047031",
                               "#8bba40",
                               "#fee11d")) +
  theme(
    panel.grid = element_blank(), # Removes all grid lines
    axis.title.x = element_text(margin = margin(t = 15)),  # Add space above x-axis title
    axis.title.y = element_text(margin = margin(r = 15)),   # Add space to the right of y-axis title
    text = element_text(family = "Verdana")
  )

consensus_plot$labels$fill <- "Caller"

consensus_plot

ggsave("consensus_counts.png")
```


```{r, echo=FALSE, message=FALSE}
# Creating data frame of all structural variants for each chromosome by caller
aggregate_counts2 <- aml_counts %>% 
  group_by(SV, Caller, Chromosome) %>% 
  summarize(Total_Counts = sum(Count)) %>% 
  ungroup()

#filtering down to chr1 & chr2 for comparison with test data
filtered <- aggregate_counts2 %>% 
  filter(Chromosome %in% c("chr1", "chr2"))

chr1_chr2_plot <- ggplot(filtered, aes(x=SV, y=Total_Counts, fill=Caller)) +
  geom_bar(position=position_dodge(), stat="identity") +
  theme_bw() +
  xlab("Structural Variant Type") +
  ylab("Count") +
  facet_wrap(~Chromosome, labeller = as_labeller(c("chr1" = "Chromosome 1", "chr2" = "Chromosome 2"))) +
  ggtitle("Frequency of Structural Variants by Caller Across Chromosomes: \nFull Consensus Data") +
  scale_fill_manual(values = c("#047031",
                               "#8bba40",
                               "#fee11d")) +
  theme(
    panel.grid = element_blank(), # Getting rid of grid lines
    strip.background = element_rect(fill = "#8bba40", color = "black"), # Fill facet titles with color
    strip.text = element_text(color = "black", face = "bold"),
    axis.title.x = element_text(margin = margin(t = 15)),  # Add space above x-axis title
    axis.title.y = element_text(margin = margin(r = 15)),   # Add space to the right of y-axis title
    text = element_text(family = "Verdana")
  )


chr1_chr2_plot$labels$fill <- "Caller"

chr1_chr2_plot

ggsave("consensus_counts_chr1&2.png")
```
